name: alinux-Kali
on: 
defaults:
  run:
    shell: bash
    
jobs:
  build:
    name: Linux System Build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
 ##   - name: If failed, means ok
 ##     run: ./not-exist-file.sh it bloke build
    - name: ======[Running Kali Docker]======
    ##  if: ${{ failure() }}
      run: bash KaliXrdp.sh ; sleep 8
