
name: alinux-Kali
on: 
  workflow_dispatch:
   inputs:
      crdauthcode:
        description: 'Enter ChromeRemoteDesktop Headless code'
        required: true
      pincode:
        description: 'Six digit Pin'
        required: true
defaults:
  run:
    shell: bash
    
jobs:
  build:
    name: Linux System Build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
 ##   - name: If failed, means ok
 ##     run: ./not-exist-file.sh it bloke build
    - name: Setting Up the Ubuntu Environment
    ##  if: ${{ failure() }}
      run: bash KaliXrdp.sh ; sleep 6h
