name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: step-1
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: step-2
      run: |
        echo ====[salam]====
    - name: Analysing the code with pylint
      run: |
        echo =====[Hi Alizaw , It's working !]======
